//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildEmAll.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BuildEmAll.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -------------------------------------------------------------------------------
        ///BuildEmAll - Help version 20220327
        ///Copyright (c) 2016-2022 BuildEmAll - All Rights Reserved
        ///-------------------------------------------------------------------------------
        ///
        ///[I] About
        ///[II] Notes
        ///[III] Installation
        ///[IV] How To Build ROMs, Patches and Datafiles
        ///[V] How To Build PPDs
        ///[VI] FAQ
        ///[VII] Contributing
        ///[VIII] Contact
        ///[IX] Disclaimers
        ///
        ///[I] About
        ///---------------------------------------------------------------- [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BuildEmAll_HELP {
            get {
                return ResourceManager.GetString("BuildEmAll_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BuildEmAll_HELP_CMD {
            get {
                return ResourceManager.GetString("BuildEmAll_HELP_CMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -------------------------------------------------------------------------------
        ///BuildEmAll - License version 20220327
        ///Copyright (c) 2016-2022 BuildEmAll - All Rights Reserved
        ///***************************************************************
        ///
        ///TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION
        ///
        ///1. Redistributions in any form are not permitted whatsoever,
        ///under any conditions.
        ///
        ///2. This software may not be reverse engineered, decompiled,
        ///or disassembled.
        ///
        ///3. BuildEmAll may publish revised a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BuildEmAll_LICENSE {
            get {
                return ResourceManager.GetString("BuildEmAll_LICENSE", resourceCulture);
            }
        }
    }
}
